version: 2.1

orbs:
  go-module: timakin/go-module@0.0.5
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9

executors:
  test:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/po3rin/llb2dot

jobs:
  test:
    executor:
      name: test
    steps:
      - checkout
      - setup_remote_docker
      - go-module/setup

      # - run:
      #     name: Setup Code Climate test-reporter
      #     command: |
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter

      - run:
          name: Run tests
          command: |
            # ./cc-test-reporter before-build
            go test ./... -coverprofile=c.out
            # ./cc-test-reporter after-build -d -r $CODE_CLIMATE_TOKEN --coverage-input-type gocov -p ./ --exit-code $?
      - run:
          name: Convert html
          command: go tool cover -html c.out -o c.html

      - store_artifacts:
          path: c.out
          destination: c.out

      - store_artifacts:
          path: c.html
          destination: c.html

workflows:
  version: 2.0
  test_build_deploy:
    jobs:
      - test
